### PR TITLE
Fix katex_js path

### LINKED ISSUE #13: Incorrect path output for KaTeX js
Currently the log output shows:
```
Katex Configuration: Found KaTeX js at: ~/lib/assets/js//katex.min.js
```
Notice the double slash `//` between the `:js_path` and the `:js_filename` values

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #13 

JS path shouldn't contain double slashes.

### CODE REVIEW

File: lib/jekyll-katex/configuration.rb [hunk 1]
```diff
@@ -10,7 +10,7 @@ class Configuration
       LOG_TOPIC = 'Katex Configuration:'
       CONFIG_DEFAULTS = {
         js_filename: 'katex.min.js',
-        js_path: File.join(Jekyll::Katex::LIB_ROOT, 'assets/js/'),
+        js_path: File.join(Jekyll::Katex::LIB_ROOT, 'assets/js'),
```
Comment (linjer) [inline lib/jekyll-katex/configuration.rb]:
```suggestion
        js_path: File.join(Jekyll::Katex::LIB_ROOT, 'assets', 'js'),
```

I guess part of the issue is hard-coding the path separator. Would prefer removing its use completely and simply rely on `File.join`.

Comment (linjer) [reply lib/jekyll-katex/configuration.rb]: Similar change might be preferred on line 26:

```ruby
katex_js = Dir.glob(File.join(js_path, '**', js_filename).first
```

**Review by linjer — CHANGES_REQUESTED** [review]
Thanks for helping!

File: lib/jekyll-katex/configuration.rb (hunk 1 above)
Comment (ashmaroli) [reply lib/jekyll-katex/configuration.rb]: Technically, `File.join` is smart in the sense that it doesn't simply join strings but produces valid paths. For example,
```ruby
File.join('root', 'assets/', '/js')
# => "root/assets/js"
```

Comment (linjer) [reply lib/jekyll-katex/configuration.rb]: Yep! I still think it's best to allow `File.join` to determine the separators and avoid hard-coding separators since we probably should support Windows users as well.

The issue with the bad path is probably more due to the lack of `File.join` on L26.

Comment (ashmaroli) [reply lib/jekyll-katex/configuration.rb]: FYI: Ruby on Windows uses `/` as separator as well.
And yes, `File.join` in L26 would've automatically resolved this as well.

Comment (linjer) [reply lib/jekyll-katex/configuration.rb]: Ah good to know. Mind fixing it in both places? I think it makes the code more robust and readable.

Please also provide any manual verification possible that this issue is fixed.

Appreciate the quick fix!

Comment (ashmaroli) [reply lib/jekyll-katex/configuration.rb]: This repo needs a proper test-suite.. :wink:
I'm not a first-hand user of this plugin. Came across this while debugging some other issue for a Jekyll user. So, I won't be able to provide a manual verification at the moment.

Comment (linjer) [reply lib/jekyll-katex/configuration.rb]: @ashmaroli Definitely needs a lot of work. Testing and automated build and release have been on the TODO forever. Hopefully, I get to it when I return in May.

Comment (ashmaroli) [reply lib/jekyll-katex/configuration.rb]: Good Luck! :smiley:

**Review by linjer — APPROVED** [review]
LGTM. Just waiting on quick verification this properly resolves the issue.

**Comment by ashmaroli** [comment]
Thank you for the opportunity. :+1:

**Comment by linjer** [comment]
I've verified this fixes the issue in #13 .
